name: Build foma

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cd foma && make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux
        path: |
          foma/foma
          foma/flookup
          foma/cgflookup
          foma/libfoma.so.*

  build-msys2:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: gcc bison flex make zlib-devel libreadline-devel ncurses-devel

    - name: Compile Foma
      run: cd foma && make

    - name: Copy MINGW64 DLLs to build directory
      run: cp /usr/bin/{msys-2.0.dll,msys-ncursesw6.dll,msys-readline8.dll,msys-z.dll} foma

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-msys2
        path: |
          foma/foma.exe
          foma/flookup.exe
          foma/cgflookup.exe
          foma/msys-2.0.dll
          foma/msys-ncursesw6.dll
          foma/msys-readline8.dll
          foma/msys-z.dll
