name: Build foma

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cd foma && make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          foma/foma
          foma/flookup
          foma/cgflookup
          foma/libfoma.so.*

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install cygwin base packages with chocolatey
      run: choco install --no-progress cygwin

    - name: Install cygwin additional packages
      run: |
        C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P bison,flex,gcc-core,libreadline-devel,zlib-devel,make
      shell: cmd

    - name: build
      run: |
        path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
        bash.exe -c "cd foma && make"
      shell: cmd

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          foma/foma.exe
          foma/flookup.exe
          foma/cgflookup.exe
          foma/libfoma.so.*
